/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesStaffingRouteImport } from './routes/services.staffing'
import { Route as ServicesRestaurantCleaningRouteImport } from './routes/services.restaurant-cleaning'
import { Route as ServicesHotelHousekeepingRouteImport } from './routes/services.hotel-housekeeping'
import { Route as ServicesCommercialCleaningRouteImport } from './routes/services.commercial-cleaning'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStaffingRoute = ServicesStaffingRouteImport.update({
  id: '/services/staffing',
  path: '/services/staffing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRestaurantCleaningRoute =
  ServicesRestaurantCleaningRouteImport.update({
    id: '/services/restaurant-cleaning',
    path: '/services/restaurant-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesHotelHousekeepingRoute =
  ServicesHotelHousekeepingRouteImport.update({
    id: '/services/hotel-housekeeping',
    path: '/services/hotel-housekeeping',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCommercialCleaningRoute =
  ServicesCommercialCleaningRouteImport.update({
    id: '/services/commercial-cleaning',
    path: '/services/commercial-cleaning',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/hotel-housekeeping': typeof ServicesHotelHousekeepingRoute
  '/services/restaurant-cleaning': typeof ServicesRestaurantCleaningRoute
  '/services/staffing': typeof ServicesStaffingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/hotel-housekeeping': typeof ServicesHotelHousekeepingRoute
  '/services/restaurant-cleaning': typeof ServicesRestaurantCleaningRoute
  '/services/staffing': typeof ServicesStaffingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/services/commercial-cleaning': typeof ServicesCommercialCleaningRoute
  '/services/hotel-housekeeping': typeof ServicesHotelHousekeepingRoute
  '/services/restaurant-cleaning': typeof ServicesRestaurantCleaningRoute
  '/services/staffing': typeof ServicesStaffingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/imprint'
    | '/privacy'
    | '/admin'
    | '/services/commercial-cleaning'
    | '/services/hotel-housekeeping'
    | '/services/restaurant-cleaning'
    | '/services/staffing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/imprint'
    | '/privacy'
    | '/admin'
    | '/services/commercial-cleaning'
    | '/services/hotel-housekeeping'
    | '/services/restaurant-cleaning'
    | '/services/staffing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/imprint'
    | '/privacy'
    | '/_authenticated/admin'
    | '/services/commercial-cleaning'
    | '/services/hotel-housekeeping'
    | '/services/restaurant-cleaning'
    | '/services/staffing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesCommercialCleaningRoute: typeof ServicesCommercialCleaningRoute
  ServicesHotelHousekeepingRoute: typeof ServicesHotelHousekeepingRoute
  ServicesRestaurantCleaningRoute: typeof ServicesRestaurantCleaningRoute
  ServicesStaffingRoute: typeof ServicesStaffingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/staffing': {
      id: '/services/staffing'
      path: '/services/staffing'
      fullPath: '/services/staffing'
      preLoaderRoute: typeof ServicesStaffingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/restaurant-cleaning': {
      id: '/services/restaurant-cleaning'
      path: '/services/restaurant-cleaning'
      fullPath: '/services/restaurant-cleaning'
      preLoaderRoute: typeof ServicesRestaurantCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hotel-housekeeping': {
      id: '/services/hotel-housekeeping'
      path: '/services/hotel-housekeeping'
      fullPath: '/services/hotel-housekeeping'
      preLoaderRoute: typeof ServicesHotelHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/commercial-cleaning': {
      id: '/services/commercial-cleaning'
      path: '/services/commercial-cleaning'
      fullPath: '/services/commercial-cleaning'
      preLoaderRoute: typeof ServicesCommercialCleaningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesCommercialCleaningRoute: ServicesCommercialCleaningRoute,
  ServicesHotelHousekeepingRoute: ServicesHotelHousekeepingRoute,
  ServicesRestaurantCleaningRoute: ServicesRestaurantCleaningRoute,
  ServicesStaffingRoute: ServicesStaffingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
